import type { ConstellationData } from "@/lib/constellations";

// The six expansion packs after The Southern Sky (SKY_REGIONS). Same 0–100
// box approximations as lib/constellationCatalog.ts. Within a pack the order
// is the reveal order: three appear when the pack is bought, then one more
// each time a constellation in it is fully charted, so recognisable ones go
// first. Like the catalog, never reorder stars once shipped.
export const PACK_CONSTELLATIONS: ConstellationData[] = [
    // The Zodiac
    {
        id: "virgo",
        region: "zodiac",
        name: "Virgo",
        commonName: "The Maiden",
        unlockAt: 0,
        stars: [
            { x: 36, y: 86, mag: 1, name: "Spica" },
            { x: 40, y: 52, mag: 2, name: "Porrima" },
            { x: 78, y: 22, mag: 2, name: "Vindemiatrix" },
            { x: 60, y: 44, mag: 3, name: "Minelauva" },
            { x: 62, y: 70, mag: 3, name: "Heze" },
            { x: 22, y: 44, mag: 3, name: "Zaniah" },
            { x: 8, y: 36, mag: 3, name: "Zavijava" },
        ],
        edges: [[6, 5], [5, 1], [1, 3], [3, 2], [1, 0], [3, 4], [4, 0]],
    },
    {
        id: "aquarius",
        region: "zodiac",
        name: "Aquarius",
        commonName: "The Water Bearer",
        unlockAt: 0,
        stars: [
            { x: 20, y: 26, mag: 2, name: "Sadalsuud" },
            { x: 46, y: 24, mag: 2, name: "Sadalmelik" },
            { x: 62, y: 28, mag: 3, name: "Sadachbia" },
            { x: 44, y: 46, mag: 3, name: "Ancha" },
            { x: 52, y: 62, mag: 3 },
            { x: 46, y: 84, mag: 2, name: "Skat" },
            { x: 78, y: 70, mag: 3 },
        ],
        edges: [[0, 1], [1, 2], [1, 3], [3, 4], [4, 5], [4, 6]],
    },
    {
        id: "capricornus",
        region: "zodiac",
        name: "Capricornus",
        commonName: "The Sea Goat",
        unlockAt: 0,
        stars: [
            { x: 12, y: 38, mag: 2, name: "Deneb Algedi" },
            { x: 26, y: 42, mag: 3, name: "Nashira" },
            { x: 86, y: 22, mag: 2, name: "Algedi" },
            { x: 80, y: 34, mag: 2, name: "Dabih" },
            { x: 70, y: 74, mag: 3 },
            { x: 44, y: 70, mag: 3 },
        ],
        edges: [[2, 3], [3, 4], [4, 5], [5, 0], [0, 1], [1, 3]],
    },
    {
        id: "aries",
        region: "zodiac",
        name: "Aries",
        commonName: "The Ram",
        unlockAt: 0,
        stars: [
            { x: 34, y: 40, mag: 1, name: "Hamal" },
            { x: 62, y: 56, mag: 2, name: "Sheratan" },
            { x: 70, y: 68, mag: 3, name: "Mesarthim" },
            { x: 10, y: 30, mag: 3, name: "Bharani" },
        ],
        edges: [[3, 0], [0, 1], [1, 2]],
    },
    {
        id: "pisces",
        region: "zodiac",
        name: "Pisces",
        commonName: "The Fishes",
        unlockAt: 0,
        stars: [
            { x: 14, y: 84, mag: 2, name: "Alrescha" },
            { x: 22, y: 56, mag: 2, name: "Alpherg" },
            { x: 28, y: 30, mag: 3 },
            { x: 40, y: 76, mag: 3 },
            { x: 66, y: 72, mag: 3 },
            { x: 84, y: 62, mag: 3, name: "Fumalsamakah" },
            { x: 76, y: 50, mag: 3 },
        ],
        edges: [[0, 1], [1, 2], [0, 3], [3, 4], [4, 5], [5, 6], [6, 4]],
    },
    {
        id: "cancer",
        region: "zodiac",
        name: "Cancer",
        commonName: "The Crab",
        unlockAt: 0,
        stars: [
            { x: 78, y: 82, mag: 2, name: "Tarf" },
            { x: 50, y: 52, mag: 2, name: "Asellus Australis" },
            { x: 48, y: 32, mag: 3, name: "Asellus Borealis" },
            { x: 26, y: 80, mag: 3, name: "Acubens" },
            { x: 42, y: 10, mag: 3 },
        ],
        edges: [[4, 2], [2, 1], [1, 0], [1, 3]],
    },
    {
        id: "libra",
        region: "zodiac",
        name: "Libra",
        commonName: "The Scales",
        unlockAt: 0,
        stars: [
            { x: 56, y: 20, mag: 2, name: "Zubeneschamali" },
            { x: 22, y: 48, mag: 2, name: "Zubenelgenubi" },
            { x: 76, y: 52, mag: 3, name: "Zubenelhakrabi" },
            { x: 28, y: 80, mag: 3, name: "Brachium" },
            { x: 72, y: 84, mag: 3 },
        ],
        edges: [[0, 1], [0, 2], [1, 2], [1, 3], [2, 4]],
    },
    {
        id: "ophiuchus",
        region: "zodiac",
        name: "Ophiuchus",
        commonName: "The Serpent Bearer",
        unlockAt: 0,
        stars: [
            { x: 48, y: 10, mag: 1, name: "Rasalhague" },
            { x: 68, y: 30, mag: 2, name: "Cebalrai" },
            { x: 28, y: 50, mag: 2, name: "Yed Prior" },
            { x: 70, y: 70, mag: 2, name: "Sabik" },
            { x: 40, y: 74, mag: 2, name: "Han" },
            { x: 26, y: 26, mag: 3 },
            { x: 62, y: 90, mag: 3 },
        ],
        edges: [[0, 5], [0, 1], [5, 2], [2, 4], [4, 3], [1, 3], [3, 6]],
    },

    // Heroes & Legends
    {
        id: "perseus",
        region: "heroes",
        name: "Perseus",
        commonName: "The Hero",
        unlockAt: 0,
        stars: [
            { x: 50, y: 34, mag: 1, name: "Mirfak" },
            { x: 34, y: 62, mag: 2, name: "Algol" },
            { x: 64, y: 20, mag: 3 },
            { x: 70, y: 48, mag: 3 },
            { x: 78, y: 70, mag: 3 },
            { x: 80, y: 88, mag: 3, name: "Menkib" },
            { x: 22, y: 80, mag: 3 },
            { x: 40, y: 12, mag: 3, name: "Miram" },
        ],
        edges: [[7, 0], [2, 0], [0, 3], [3, 4], [4, 5], [0, 1], [1, 6]],
    },
    {
        id: "hercules",
        region: "heroes",
        name: "Hercules",
        commonName: "The Strongman",
        unlockAt: 0,
        stars: [
            { x: 70, y: 30, mag: 1, name: "Kornephoros" },
            { x: 84, y: 82, mag: 2, name: "Rasalgethi" },
            { x: 52, y: 40, mag: 3 },
            { x: 42, y: 28, mag: 3 },
            { x: 48, y: 58, mag: 3 },
            { x: 32, y: 52, mag: 3 },
            { x: 68, y: 62, mag: 2, name: "Sarin" },
            { x: 20, y: 14, mag: 3 },
        ],
        edges: [[2, 3], [3, 5], [5, 4], [4, 2], [2, 0], [4, 6], [6, 1], [3, 7]],
    },
    {
        id: "bootes",
        region: "heroes",
        name: "Boötes",
        commonName: "The Herdsman",
        unlockAt: 0,
        stars: [
            { x: 50, y: 86, mag: 1, name: "Arcturus" },
            { x: 70, y: 54, mag: 2, name: "Izar" },
            { x: 28, y: 76, mag: 3, name: "Muphrid" },
            { x: 30, y: 40, mag: 2, name: "Seginus" },
            { x: 50, y: 12, mag: 3, name: "Nekkar" },
            { x: 68, y: 34, mag: 3, name: "Princeps" },
        ],
        edges: [[0, 1], [1, 5], [5, 4], [4, 3], [3, 0], [0, 2]],
    },
    {
        id: "auriga",
        region: "heroes",
        name: "Auriga",
        commonName: "The Charioteer",
        unlockAt: 0,
        stars: [
            { x: 30, y: 16, mag: 1, name: "Capella" },
            { x: 66, y: 20, mag: 2, name: "Menkalinan" },
            { x: 82, y: 54, mag: 3, name: "Mahasim" },
            { x: 28, y: 76, mag: 2, name: "Hassaleh" },
            { x: 14, y: 32, mag: 3, name: "Almaaz" },
            { x: 20, y: 46, mag: 3, name: "Haedus" },
        ],
        edges: [[0, 1], [1, 2], [2, 3], [3, 0], [0, 4], [4, 5]],
    },
    {
        id: "cepheus",
        region: "heroes",
        name: "Cepheus",
        commonName: "The King",
        unlockAt: 0,
        stars: [
            { x: 30, y: 62, mag: 1, name: "Alderamin" },
            { x: 48, y: 32, mag: 2, name: "Alfirk" },
            { x: 70, y: 14, mag: 2, name: "Errai" },
            { x: 78, y: 54, mag: 3 },
            { x: 54, y: 74, mag: 3 },
            { x: 66, y: 88, mag: 3, name: "Delta Cephei" },
        ],
        edges: [[0, 1], [1, 2], [2, 3], [3, 4], [4, 0], [1, 3], [4, 5]],
    },
    {
        id: "cetus",
        region: "heroes",
        name: "Cetus",
        commonName: "The Sea Monster",
        unlockAt: 0,
        stars: [
            { x: 14, y: 72, mag: 1, name: "Diphda" },
            { x: 82, y: 32, mag: 2, name: "Menkar" },
            { x: 58, y: 48, mag: 2, name: "Mira" },
            { x: 72, y: 22, mag: 3, name: "Kaffaljidhma" },
            { x: 40, y: 60, mag: 3, name: "Baten Kaitos" },
            { x: 90, y: 14, mag: 3 },
            { x: 30, y: 84, mag: 3 },
        ],
        edges: [[1, 3], [3, 5], [5, 1], [1, 2], [2, 4], [4, 0], [0, 6], [6, 4]],
    },
    {
        id: "corona-borealis",
        region: "heroes",
        name: "Corona Borealis",
        commonName: "The Northern Crown",
        unlockAt: 0,
        stars: [
            { x: 46, y: 64, mag: 1, name: "Alphecca" },
            { x: 26, y: 52, mag: 3, name: "Nusakan" },
            { x: 12, y: 32, mag: 3 },
            { x: 66, y: 60, mag: 3 },
            { x: 80, y: 48, mag: 3 },
            { x: 88, y: 30, mag: 3 },
        ],
        edges: [[2, 1], [1, 0], [0, 3], [3, 4], [4, 5]],
    },
    {
        id: "serpens",
        region: "heroes",
        name: "Serpens",
        commonName: "The Serpent",
        unlockAt: 0,
        stars: [
            { x: 40, y: 50, mag: 1, name: "Unukalhai" },
            { x: 30, y: 30, mag: 3 },
            { x: 40, y: 14, mag: 3 },
            { x: 22, y: 20, mag: 3 },
            { x: 48, y: 64, mag: 3 },
            { x: 60, y: 78, mag: 3 },
            { x: 76, y: 70, mag: 3 },
            { x: 92, y: 52, mag: 3, name: "Alya" },
        ],
        edges: [[2, 1], [1, 3], [3, 2], [1, 0], [0, 4], [4, 5], [5, 6], [6, 7]],
    },

    // The Long River
    {
        id: "canis-minor",
        region: "river",
        name: "Canis Minor",
        commonName: "The Little Dog",
        unlockAt: 0,
        stars: [
            { x: 36, y: 62, mag: 1, name: "Procyon" },
            { x: 66, y: 38, mag: 2, name: "Gomeisa" },
        ],
        edges: [[0, 1]],
    },
    {
        id: "lepus",
        region: "river",
        name: "Lepus",
        commonName: "The Hare",
        unlockAt: 0,
        stars: [
            { x: 48, y: 40, mag: 1, name: "Arneb" },
            { x: 40, y: 62, mag: 2, name: "Nihal" },
            { x: 68, y: 36, mag: 3 },
            { x: 78, y: 62, mag: 3 },
            { x: 30, y: 20, mag: 3 },
            { x: 16, y: 30, mag: 3 },
            { x: 60, y: 80, mag: 3 },
        ],
        edges: [[5, 4], [4, 0], [0, 2], [2, 3], [3, 6], [6, 1], [1, 0]],
    },
    {
        id: "eridanus",
        region: "river",
        name: "Eridanus",
        commonName: "The River",
        unlockAt: 0,
        stars: [
            { x: 12, y: 92, mag: 1, name: "Achernar" },
            { x: 90, y: 8, mag: 2, name: "Cursa" },
            { x: 78, y: 18, mag: 3, name: "Rana" },
            { x: 64, y: 22, mag: 3, name: "Ran" },
            { x: 48, y: 16, mag: 3, name: "Azha" },
            { x: 56, y: 38, mag: 2, name: "Zaurak" },
            { x: 30, y: 58, mag: 2, name: "Acamar" },
            { x: 34, y: 78, mag: 3 },
        ],
        edges: [[1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7], [7, 0]],
    },
    {
        id: "hydra",
        region: "river",
        name: "Hydra",
        commonName: "The Water Snake",
        unlockAt: 0,
        stars: [
            { x: 30, y: 50, mag: 1, name: "Alphard" },
            { x: 10, y: 22, mag: 3, name: "Ashlesha" },
            { x: 16, y: 12, mag: 3 },
            { x: 24, y: 22, mag: 3 },
            { x: 18, y: 36, mag: 3 },
            { x: 48, y: 60, mag: 3 },
            { x: 64, y: 58, mag: 3 },
            { x: 80, y: 74, mag: 2 },
            { x: 94, y: 86, mag: 3 },
        ],
        edges: [[1, 2], [2, 3], [3, 4], [4, 1], [4, 0], [0, 5], [5, 6], [6, 7], [7, 8]],
    },
    {
        id: "corvus",
        region: "river",
        name: "Corvus",
        commonName: "The Crow",
        unlockAt: 0,
        stars: [
            { x: 20, y: 30, mag: 2, name: "Gienah" },
            { x: 70, y: 74, mag: 2, name: "Kraz" },
            { x: 66, y: 30, mag: 2, name: "Algorab" },
            { x: 22, y: 66, mag: 3, name: "Minkar" },
            { x: 10, y: 84, mag: 3, name: "Alchiba" },
        ],
        edges: [[0, 2], [2, 1], [1, 3], [3, 0], [3, 4]],
    },
    {
        id: "monoceros",
        region: "river",
        name: "Monoceros",
        commonName: "The Unicorn",
        unlockAt: 0,
        stars: [
            { x: 70, y: 72, mag: 2 },
            { x: 50, y: 52, mag: 3 },
            { x: 36, y: 36, mag: 3 },
            { x: 20, y: 20, mag: 3 },
            { x: 68, y: 30, mag: 3 },
        ],
        edges: [[0, 1], [1, 2], [2, 3], [1, 4]],
    },
    {
        id: "puppis",
        region: "river",
        name: "Puppis",
        commonName: "The Stern",
        unlockAt: 0,
        stars: [
            { x: 60, y: 20, mag: 1, name: "Naos" },
            { x: 30, y: 40, mag: 2, name: "Tureis" },
            { x: 72, y: 62, mag: 3, name: "Azmidi" },
            { x: 42, y: 82, mag: 2, name: "Ahadi" },
            { x: 20, y: 62, mag: 3 },
            { x: 84, y: 86, mag: 3 },
        ],
        edges: [[0, 1], [1, 4], [4, 3], [3, 5], [5, 2], [2, 0]],
    },
    {
        id: "columba",
        region: "river",
        name: "Columba",
        commonName: "The Dove",
        unlockAt: 0,
        stars: [
            { x: 40, y: 40, mag: 1, name: "Phact" },
            { x: 60, y: 52, mag: 2, name: "Wazn" },
            { x: 82, y: 36, mag: 3 },
            { x: 20, y: 58, mag: 3 },
            { x: 70, y: 80, mag: 3 },
        ],
        edges: [[3, 0], [0, 1], [1, 2], [1, 4]],
    },
    {
        id: "crater",
        region: "river",
        name: "Crater",
        commonName: "The Cup",
        unlockAt: 0,
        stars: [
            { x: 50, y: 42, mag: 2, name: "Labrum" },
            { x: 84, y: 72, mag: 3, name: "Alkes" },
            { x: 64, y: 82, mag: 3 },
            { x: 32, y: 40, mag: 3 },
            { x: 24, y: 20, mag: 3 },
            { x: 64, y: 20, mag: 3 },
        ],
        edges: [[4, 3], [3, 0], [0, 5], [0, 1], [1, 2], [2, 3]],
    },
    {
        id: "sextans",
        region: "river",
        name: "Sextans",
        commonName: "The Sextant",
        unlockAt: 0,
        stars: [
            { x: 40, y: 40, mag: 2 },
            { x: 70, y: 60, mag: 3 },
            { x: 20, y: 70, mag: 3 },
            { x: 80, y: 30, mag: 3 },
        ],
        edges: [[2, 0], [0, 3], [0, 1]],
    },

    // The Deep South
    {
        id: "piscis-austrinus",
        region: "deep-south",
        name: "Piscis Austrinus",
        commonName: "The Southern Fish",
        unlockAt: 0,
        stars: [
            { x: 20, y: 40, mag: 1, name: "Fomalhaut" },
            { x: 40, y: 58, mag: 3 },
            { x: 60, y: 50, mag: 3 },
            { x: 80, y: 60, mag: 3 },
            { x: 70, y: 30, mag: 3 },
            { x: 46, y: 30, mag: 3 },
        ],
        edges: [[0, 1], [1, 2], [2, 3], [3, 4], [4, 5], [5, 0]],
    },
    {
        id: "dorado",
        region: "deep-south",
        name: "Dorado",
        commonName: "The Swordfish",
        unlockAt: 0,
        stars: [
            { x: 20, y: 20, mag: 2 },
            { x: 40, y: 40, mag: 3 },
            { x: 56, y: 52, mag: 2 },
            { x: 76, y: 72, mag: 3 },
            { x: 36, y: 22, mag: 3 },
        ],
        edges: [[0, 4], [0, 1], [1, 2], [2, 3]],
    },
    {
        id: "musca",
        region: "deep-south",
        name: "Musca",
        commonName: "The Fly",
        unlockAt: 0,
        stars: [
            { x: 40, y: 40, mag: 2 },
            { x: 60, y: 50, mag: 3 },
            { x: 20, y: 30, mag: 3 },
            { x: 30, y: 70, mag: 3 },
            { x: 70, y: 20, mag: 3 },
        ],
        edges: [[4, 2], [2, 0], [0, 1], [0, 3]],
    },
    {
        id: "ara",
        region: "deep-south",
        name: "Ara",
        commonName: "The Altar",
        unlockAt: 0,
        stars: [
            { x: 50, y: 30, mag: 2 },
            { x: 30, y: 40, mag: 3 },
            { x: 66, y: 50, mag: 3 },
            { x: 74, y: 80, mag: 3 },
            { x: 30, y: 80, mag: 3 },
            { x: 20, y: 60, mag: 3 },
        ],
        edges: [[0, 1], [0, 2], [2, 3], [1, 5], [5, 4]],
    },
    {
        id: "hydrus",
        region: "deep-south",
        name: "Hydrus",
        commonName: "The Male Water Snake",
        unlockAt: 0,
        stars: [
            { x: 20, y: 20, mag: 2 },
            { x: 80, y: 40, mag: 2 },
            { x: 50, y: 84, mag: 2 },
            { x: 60, y: 52, mag: 3 },
        ],
        edges: [[0, 1], [1, 3], [3, 2], [2, 0]],
    },
    {
        id: "indus",
        region: "deep-south",
        name: "Indus",
        commonName: "The Indian",
        unlockAt: 0,
        stars: [
            { x: 40, y: 20, mag: 2, name: "The Persian" },
            { x: 40, y: 70, mag: 3 },
            { x: 70, y: 58, mag: 3 },
            { x: 80, y: 84, mag: 3 },
        ],
        edges: [[0, 2], [2, 1], [1, 0], [2, 3]],
    },
    {
        id: "apus",
        region: "deep-south",
        name: "Apus",
        commonName: "The Bird of Paradise",
        unlockAt: 0,
        stars: [
            { x: 20, y: 40, mag: 2 },
            { x: 70, y: 56, mag: 3 },
            { x: 82, y: 70, mag: 3 },
            { x: 60, y: 74, mag: 3 },
        ],
        edges: [[0, 3], [3, 2], [2, 1], [1, 3]],
    },
    {
        id: "volans",
        region: "deep-south",
        name: "Volans",
        commonName: "The Flying Fish",
        unlockAt: 0,
        stars: [
            { x: 30, y: 30, mag: 3 },
            { x: 60, y: 40, mag: 3 },
            { x: 80, y: 56, mag: 3 },
            { x: 70, y: 80, mag: 2 },
            { x: 40, y: 70, mag: 3 },
        ],
        edges: [[0, 1], [1, 2], [2, 3], [3, 4], [4, 1]],
    },
    {
        id: "scutum",
        region: "deep-south",
        name: "Scutum",
        commonName: "The Shield",
        unlockAt: 0,
        stars: [
            { x: 40, y: 40, mag: 2 },
            { x: 60, y: 24, mag: 3 },
            { x: 70, y: 62, mag: 3 },
            { x: 50, y: 80, mag: 3 },
        ],
        edges: [[0, 1], [1, 2], [2, 3], [3, 0]],
    },
    {
        id: "chamaeleon",
        region: "deep-south",
        name: "Chamaeleon",
        commonName: "The Chameleon",
        unlockAt: 0,
        stars: [
            { x: 20, y: 40, mag: 2 },
            { x: 40, y: 30, mag: 3 },
            { x: 80, y: 62, mag: 3 },
            { x: 60, y: 70, mag: 3 },
        ],
        edges: [[0, 1], [1, 3], [3, 2], [0, 3]],
    },

    // Small Wonders
    {
        id: "delphinus",
        region: "small-wonders",
        name: "Delphinus",
        commonName: "The Dolphin",
        unlockAt: 0,
        stars: [
            { x: 30, y: 40, mag: 2, name: "Rotanev" },
            { x: 50, y: 30, mag: 2, name: "Sualocin" },
            { x: 68, y: 40, mag: 3 },
            { x: 46, y: 52, mag: 3 },
            { x: 20, y: 72, mag: 3, name: "Aldulfin" },
        ],
        edges: [[0, 1], [1, 2], [2, 3], [3, 0], [0, 4]],
    },
    {
        id: "triangulum",
        region: "small-wonders",
        name: "Triangulum",
        commonName: "The Triangle",
        unlockAt: 0,
        stars: [
            { x: 20, y: 60, mag: 2, name: "Mothallah" },
            { x: 70, y: 30, mag: 2 },
            { x: 78, y: 50, mag: 3 },
        ],
        edges: [[0, 1], [1, 2], [2, 0]],
    },
    {
        id: "coma-berenices",
        region: "small-wonders",
        name: "Coma Berenices",
        commonName: "Berenice's Hair",
        unlockAt: 0,
        stars: [
            { x: 30, y: 70, mag: 2, name: "Diadem" },
            { x: 70, y: 72, mag: 3 },
            { x: 70, y: 26, mag: 3 },
        ],
        edges: [[0, 1], [1, 2]],
    },
    {
        id: "canes-venatici",
        region: "small-wonders",
        name: "Canes Venatici",
        commonName: "The Hunting Dogs",
        unlockAt: 0,
        stars: [
            { x: 30, y: 60, mag: 1, name: "Cor Caroli" },
            { x: 70, y: 36, mag: 2, name: "Chara" },
        ],
        edges: [[0, 1]],
    },
    {
        id: "sagitta",
        region: "small-wonders",
        name: "Sagitta",
        commonName: "The Arrow",
        unlockAt: 0,
        stars: [
            { x: 30, y: 50, mag: 3, name: "Sham" },
            { x: 40, y: 62, mag: 3 },
            { x: 60, y: 48, mag: 3 },
            { x: 86, y: 36, mag: 2 },
        ],
        edges: [[0, 2], [1, 2], [2, 3]],
    },
    {
        id: "lacerta",
        region: "small-wonders",
        name: "Lacerta",
        commonName: "The Lizard",
        unlockAt: 0,
        stars: [
            { x: 50, y: 20, mag: 2 },
            { x: 40, y: 30, mag: 3 },
            { x: 56, y: 40, mag: 3 },
            { x: 44, y: 52, mag: 3 },
            { x: 58, y: 64, mag: 3 },
            { x: 40, y: 84, mag: 3 },
        ],
        edges: [[0, 1], [1, 2], [2, 3], [3, 4], [4, 5]],
    },
    {
        id: "vulpecula",
        region: "small-wonders",
        name: "Vulpecula",
        commonName: "The Little Fox",
        unlockAt: 0,
        stars: [
            { x: 40, y: 40, mag: 2, name: "Anser" },
            { x: 20, y: 60, mag: 3 },
            { x: 70, y: 30, mag: 3 },
        ],
        edges: [[1, 0], [0, 2]],
    },
    {
        id: "equuleus",
        region: "small-wonders",
        name: "Equuleus",
        commonName: "The Little Horse",
        unlockAt: 0,
        stars: [
            { x: 30, y: 62, mag: 2, name: "Kitalpha" },
            { x: 66, y: 58, mag: 3 },
            { x: 70, y: 32, mag: 3 },
            { x: 34, y: 30, mag: 3 },
        ],
        edges: [[0, 1], [1, 2], [2, 3], [3, 0]],
    },
    {
        id: "leo-minor",
        region: "small-wonders",
        name: "Leo Minor",
        commonName: "The Little Lion",
        unlockAt: 0,
        stars: [
            { x: 30, y: 40, mag: 2, name: "Praecipua" },
            { x: 60, y: 50, mag: 3 },
            { x: 80, y: 30, mag: 3 },
            { x: 40, y: 62, mag: 3 },
        ],
        edges: [[0, 1], [1, 2], [0, 3]],
    },
    {
        id: "lynx",
        region: "small-wonders",
        name: "Lynx",
        commonName: "The Lynx",
        unlockAt: 0,
        stars: [
            { x: 84, y: 86, mag: 2 },
            { x: 76, y: 70, mag: 3 },
            { x: 60, y: 56, mag: 3 },
            { x: 44, y: 40, mag: 3 },
            { x: 30, y: 26, mag: 3 },
            { x: 16, y: 12, mag: 3 },
        ],
        edges: [[0, 1], [1, 2], [2, 3], [3, 4], [4, 5]],
    },
    {
        id: "camelopardalis",
        region: "small-wonders",
        name: "Camelopardalis",
        commonName: "The Giraffe",
        unlockAt: 0,
        stars: [
            { x: 40, y: 60, mag: 2 },
            { x: 50, y: 40, mag: 3 },
            { x: 60, y: 24, mag: 3 },
            { x: 28, y: 76, mag: 3 },
            { x: 70, y: 70, mag: 3 },
        ],
        edges: [[3, 0], [0, 1], [1, 2], [0, 4]],
    },

    // Instruments of Science
    {
        id: "pyxis",
        region: "instruments",
        name: "Pyxis",
        commonName: "The Compass",
        unlockAt: 0,
        stars: [
            { x: 50, y: 50, mag: 2 },
            { x: 40, y: 72, mag: 3 },
            { x: 60, y: 24, mag: 3 },
        ],
        edges: [[1, 0], [0, 2]],
    },
    {
        id: "octans",
        region: "instruments",
        name: "Octans",
        commonName: "The Octant",
        unlockAt: 0,
        stars: [
            { x: 30, y: 70, mag: 2 },
            { x: 70, y: 30, mag: 3 },
            { x: 80, y: 80, mag: 3 },
            { x: 50, y: 18, mag: 3, name: "Polaris Australis" },
        ],
        edges: [[0, 1], [1, 2], [2, 0]],
    },
    {
        id: "telescopium",
        region: "instruments",
        name: "Telescopium",
        commonName: "The Telescope",
        unlockAt: 0,
        stars: [
            { x: 40, y: 40, mag: 2 },
            { x: 60, y: 70, mag: 3 },
            { x: 24, y: 60, mag: 3 },
        ],
        edges: [[2, 0], [0, 1]],
    },
    {
        id: "horologium",
        region: "instruments",
        name: "Horologium",
        commonName: "The Clock",
        unlockAt: 0,
        stars: [
            { x: 80, y: 20, mag: 2 },
            { x: 60, y: 40, mag: 3 },
            { x: 40, y: 62, mag: 3 },
            { x: 30, y: 80, mag: 3 },
            { x: 50, y: 86, mag: 3 },
        ],
        edges: [[0, 1], [1, 2], [2, 3], [3, 4]],
    },
    {
        id: "circinus",
        region: "instruments",
        name: "Circinus",
        commonName: "The Drafting Compass",
        unlockAt: 0,
        stars: [
            { x: 30, y: 70, mag: 2 },
            { x: 60, y: 20, mag: 3 },
            { x: 76, y: 30, mag: 3 },
        ],
        edges: [[0, 1], [0, 2]],
    },
    {
        id: "norma",
        region: "instruments",
        name: "Norma",
        commonName: "The Carpenter's Square",
        unlockAt: 0,
        stars: [
            { x: 30, y: 30, mag: 2 },
            { x: 70, y: 30, mag: 3 },
            { x: 70, y: 70, mag: 3 },
            { x: 30, y: 70, mag: 3 },
        ],
        edges: [[0, 1], [1, 2], [2, 3], [3, 0]],
    },
    {
        id: "microscopium",
        region: "instruments",
        name: "Microscopium",
        commonName: "The Microscope",
        unlockAt: 0,
        stars: [
            { x: 30, y: 30, mag: 3 },
            { x: 70, y: 26, mag: 2 },
            { x: 74, y: 70, mag: 3 },
            { x: 34, y: 74, mag: 3 },
        ],
        edges: [[0, 1], [1, 2], [2, 3], [3, 0]],
    },
    {
        id: "reticulum",
        region: "instruments",
        name: "Reticulum",
        commonName: "The Reticle",
        unlockAt: 0,
        stars: [
            { x: 30, y: 30, mag: 2 },
            { x: 70, y: 30, mag: 3 },
            { x: 70, y: 70, mag: 3 },
            { x: 30, y: 70, mag: 3 },
        ],
        edges: [[0, 1], [1, 2], [2, 3], [3, 0]],
    },
    {
        id: "fornax",
        region: "instruments",
        name: "Fornax",
        commonName: "The Furnace",
        unlockAt: 0,
        stars: [
            { x: 30, y: 60, mag: 2, name: "Dalim" },
            { x: 60, y: 40, mag: 3 },
            { x: 80, y: 30, mag: 3 },
        ],
        edges: [[0, 1], [1, 2]],
    },
    {
        id: "sculptor",
        region: "instruments",
        name: "Sculptor",
        commonName: "The Sculptor",
        unlockAt: 0,
        stars: [
            { x: 20, y: 40, mag: 2 },
            { x: 60, y: 46, mag: 3 },
            { x: 80, y: 60, mag: 3 },
            { x: 70, y: 30, mag: 3 },
        ],
        edges: [[0, 1], [1, 2], [2, 3], [3, 1]],
    },
    {
        id: "pictor",
        region: "instruments",
        name: "Pictor",
        commonName: "The Painter's Easel",
        unlockAt: 0,
        stars: [
            { x: 20, y: 80, mag: 2 },
            { x: 50, y: 50, mag: 3 },
            { x: 80, y: 20, mag: 2 },
        ],
        edges: [[0, 1], [1, 2]],
    },
    {
        id: "antlia",
        region: "instruments",
        name: "Antlia",
        commonName: "The Air Pump",
        unlockAt: 0,
        stars: [
            { x: 40, y: 40, mag: 2 },
            { x: 70, y: 30, mag: 3 },
            { x: 20, y: 60, mag: 3 },
        ],
        edges: [[1, 0], [0, 2]],
    },
    {
        id: "caelum",
        region: "instruments",
        name: "Caelum",
        commonName: "The Chisel",
        unlockAt: 0,
        stars: [
            { x: 30, y: 40, mag: 2 },
            { x: 50, y: 50, mag: 3 },
            { x: 70, y: 70, mag: 3 },
        ],
        edges: [[0, 1], [1, 2]],
    },
    {
        id: "mensa",
        region: "instruments",
        name: "Mensa",
        commonName: "Table Mountain",
        unlockAt: 0,
        stars: [
            { x: 30, y: 62, mag: 2 },
            { x: 40, y: 40, mag: 3 },
            { x: 60, y: 50, mag: 3 },
            { x: 70, y: 30, mag: 3 },
        ],
        edges: [[0, 1], [1, 2], [2, 3]],
    },
];
